### 리스트의 필요성

In [11]:
a_0 = 3 
a_1 = 2 
a_2 = 4 
a_3 = 1 
a_4 = 5

total = a_0 +a_1 + a_2 + a_3 + a_4

N = 5

print(total/N)

3


#### 리스트 평균 계산

In [19]:
a=[3,2,4,1,5]

total = sum(a)

N = len(a)

print(total/N)

3


In [12]:
print(a[0])

print(a[1])

print(a[5])

1
2


IndexError: list index out of range

In [20]:
max(a)

5

#### 행렬(numpy) 평균 계산

In [14]:
import numpy

a = numpy.array(a)

print(a)

[3 2 4 1 5]


In [15]:
total = numpy.sum(a)

print(total)

15


In [17]:
N = len(a)

print(N)

5


In [18]:
average = numpy.mean(a)

print(average)

3.0


### 리스트 연산

In [38]:
a = [1, 2, 3]
b = [4, 5, 6]

type(a)

3

In [42]:
len(a)

3

In [35]:
a+b

[1, 2, 3, 4, 5, 6]

In [39]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [41]:
len(a*3)

9

### 행렬(numpy) 연산

In [43]:
a = numpy.array(a)
b = numpy.array(b)

print(a)
print(b)

type(a)

[1 2 3]
[4 5 6]


numpy.ndarray

In [44]:
a+b

array([5, 7, 9])

In [45]:
a*3

array([3, 6, 9])

In [46]:
len(a*3)

3